name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  lepipe:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: piepline
        run: echo "hellp world"
