name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  lepipe:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: cd
        run: cd part11/full-stack-open-pokedex
      - name: install
        run: npm install
      - name: lint
        run: npm run eslint
